# Vendored from upstream tensorflow.profiler.OpStats.
# Source .proto: ./op_stats.proto (also vendored in this directory).
# To regenerate: `protoc --python_out=. op_stats.proto` from this directory.
# Do NOT edit by hand — regenerate from op_stats.proto if the schema changes.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: op_stats.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'op_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eop_stats.proto\x12\x13tensorflow.profiler\"\xbc\x01\n\x07PerfEnv\x12\"\n\x1apeak_tera_flops_per_second\x18\x01 \x01(\x01\x12)\n!peak_hbm_bw_giga_bytes_per_second\x18\x02 \x01(\x01\x12\x13\n\x0bridge_point\x18\x03 \x01(\x01\x12%\n\x1dpeak_bw_giga_bytes_per_second\x18\x04 \x01(\x01\x12&\n\x1epeak_bws_giga_bytes_per_second\x18\x05 \x03(\x01\"9\n\x07OpStats\x12.\n\x08perf_env\x18\x03 \x01(\x0b\x32\x1c.tensorflow.profiler.PerfEnvb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERFENV']._serialized_start=40
  _globals['_PERFENV']._serialized_end=228
  _globals['_OPSTATS']._serialized_start=230
  _globals['_OPSTATS']._serialized_end=287
# @@protoc_insertion_point(module_scope)
